MULLIKEN and LOEWDIN POPULATION ANALYSIS 

  atom#    atom      Mulliken charge       Loewdin charge
      1      Bi                1.45                  1.28 
      2      Bi                1.45                  1.28 
      3      Cl               -0.53                 -0.45 
      4      Cl               -0.53                 -0.45 
      5       O               -0.92                 -0.82 
      6       O               -0.92                 -0.82 

          total                0.00                 -0.00 
