Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction    Mulliken GP     Loewdin GP
                                    For spin 1     For spin 1
      1      Bi             6s           1.99           1.95
                          6p_y           0.51           0.58
                          6p_z           0.54           0.61
                          6p_x           0.51           0.58
                         5d_xy           2.00           2.00
                         5d_yz           2.00           2.00
                        5d_z^2           2.00           2.00
                         5d_xz           2.00           2.00
                    5d_x^2-y^2           2.00           2.00
                         total          13.55          13.72


      2      Bi             6s           1.99           1.95
                          6p_y           0.51           0.58
                          6p_z           0.54           0.61
                          6p_x           0.51           0.58
                         5d_xy           2.00           2.00
                         5d_yz           2.00           2.00
                        5d_z^2           2.00           2.00
                         5d_xz           2.00           2.00
                    5d_x^2-y^2           2.00           2.00
                         total          13.55          13.72


      3      Cl             3s           1.97           1.93
                          3p_y           1.83           1.82
                          3p_z           1.91           1.89
                          3p_x           1.83           1.82
                         total           7.53           7.45


      4      Cl             3s           1.97           1.93
                          3p_y           1.83           1.82
                          3p_z           1.91           1.89
                          3p_x           1.83           1.82
                         total           7.53           7.45


      5       O             2s           1.90           1.81
                          2p_y           1.67           1.67
                          2p_z           1.68           1.69
                          2p_x           1.67           1.67
                         total           6.92           6.82


      6       O             2s           1.90           1.81
                          2p_y           1.67           1.67
                          2p_z           1.68           1.69
                          2p_x           1.67           1.67
                         total           6.92           6.82

