Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Bi         -13.32          -11.85 
      2      Bi         -13.32          -11.85 
      3      Cl           4.17            3.63 
      4      Cl           4.17            3.63 
      5       O          10.06            8.89 
      6       O          10.06            8.89 

Madelung Energy (eV)    -30.71          -24.14 
